export type PPlusPortColor =
  | "Red"
  | "Blue"
  | "Green"
  | "Yellow"
  | "Purple"
  | "Pink"
  | "Orange"
  | "Brown"
  | "Black"
  | "White"
  | "Cyan"
  | "Gray";

export type PPlusTeamColor = "Red" | "Blue" | "Green";

export type PPlusCharacter =
  | "Bowser"
  | "Captain Falcon"
  | "Charizard"
  | "Donkey Kong"
  | "Diddy Kong"
  | "Dr. Mario"
  | "Falco"
  | "Fox"
  | "Ganondorf"
  | "Ice Climbers"
  | "Ike"
  | "Ivysaur"
  | "Jigglypuff"
  | "King Dedede"
  | "Kirby"
  | "Knuckles"
  | "Link"
  | "Lucario"
  | "Lucas"
  | "Luigi"
  | "Mario"
  | "Marth"
  | "Meta Knight"
  | "Mewtwo"
  | "Mr. Game & Watch"
  | "Ness"
  | "Olimar"
  | "Peach"
  | "Pichu"
  | "Pikachu"
  | "Pit"
  | "R.O.B."
  | "Roy"
  | "Samus"
  | "Sheik"
  | "Snake"
  | "Sonic"
  | "Squirtle"
  | "Toon Link"
  | "Wario"
  | "Wolf"
  | "Yoshi"
  | "Young Link"
  | "Zelda"
  | "Zero Suit Samus"
  | "Random";
